### PR TITLE
Handling Contact Request and Accepting / Declining

### PR DESCRIPTION
**Pull request by gamelaster**
Hello,

I looked to a structure of a package, it will comes to me a little chaotic! But anyway, i tryied to make it so much similiar to other codes and i integrated a Handling Contact and Accepting / Requesting.

The sending a Request from a bot IS possible (just send a PUT request to "https://api.skype.com/users/self/contacts/auth-request/SKYPENICKNAME" with data "greeting=Hi someone, i will blablabla" with SkypeToken), but actually its bugged on Skype API (when user accept that request, to Web doesnt come any event, so bot still see user as unauthorized and user see bot as offline. I think its help solve to send a ACCEPT request, not tested, but anyway, that event is i think a really needed, so we must wait to fix it at Skype side).

-gamiee

### CODE REVIEW

**Comment by ShyykoSerhiy** [comment]
Hi,
Thx, for contribution. The lib itself is written in TypeScript:) and it would be better to have changes in *.ts files. I'll rewrite your code in ts if you don't mind?

**Comment by gamelaster** [comment]
Actually, i dont know TypeScript, so if you can, i will be happy :-)

(btw. are you planning to do more things to this library? )

**Comment by ShyykoSerhiy** [comment]
Yes, I'm currently working on adding support for some features of web.skype.com:
- sending/receiving files
- searching for new contacts
- creating groups

**Comment by gamelaster** [comment]
Well,  okay,  I will do too some  but all in JavaScript if it's not a probleproblem :)

**Pull request merged**
