### PR TITLE
Use typings instead of tsd

### PR DESCRIPTION
**Pull request by d10n**
tsd has been deprecated

### CODE REVIEW

**Comment by demurgos** [comment]
Hi,
Switching from `TSD` to `typings` does not change anything if you keep using the `ambient-dependencies`. (It still causes name conflicts)
I spent the last week writing the definitions for the whole dependency tree of `skyweb`, it was mostly missing `big-integer` and we are in the process of rewriting the definitions for `request` so I was waiting to submit my PR here.
Since you've posted, I've also pushed my PR with external typings: #29.

`request` will be certainly rewritten soon, but it's already in a usable state.

**Comment by d10n** [comment]
Sorry to rush you with my low-effort PR :-) Glad that everything worked out in #29 - nice changes

**Comment by ShyykoSerhiy** [comment]
I've wanted to do this myself for ages. It's cool that you guys came up with two PR's almost simultaneously👍

**Comment by demurgos** [comment]
No problem, I did not posted here so you couldn't know ^^

**Pull request merged**
